<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div id='app'>
        <div v-for="user in users">
                <div>
                    <tr>
                        <td>{{user.id}}</td>
                        <td>{{user.username}}</td>
                    </tr>
                </div>
        </div>
    </div>
</body>
<script src='../static/Vue.js'></script>
<script src="../static/vue-resource.js"></script>
<script>
    var datas=({
        users:[],
        apiurl:'http://127.0.0.1:5000/user'
    })
    var test = new Vue({
        el:"#app",
        data:datas,
{#        html加载完后自动调用#}
        ready:function(){
          this.getUser()
        },
        methods:{
            getUser:function () {
                var self = this;
                //在编译后即调用API接口取得服务器端数据
                self.$http.get(this.apiurl)
{#                    响应成功的回调#}
                    .then((res) => {
                        self.$set('users',res.data)
{#                  响应失败的回调#}
                    },(res) => {
                        alert('error')
                    })
{#                  catch则是在整个请求到响应过程中，只要程序出错了就会被调用#}
                    .catch (function (response) {
                        console.log(response)
                    })
            }
        }
    })
</script>
</html>